/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsRouteImport } from './routes/robots'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IndexRouteImport } from './routes/index'

const RobotsRoute = RobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/robots': typeof RobotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/robots': typeof RobotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/robots': typeof RobotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/robots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/knowledge'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/robots'
  id:
    | '__root__'
    | '/'
    | '/knowledge'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/robots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PatientsRoute: typeof PatientsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ReportsRoute: typeof ReportsRoute
  RobotsRoute: typeof RobotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots': {
      id: '/robots'
      path: '/robots'
      fullPath: '/robots'
      preLoaderRoute: typeof RobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeRoute: KnowledgeRoute,
  PatientsRoute: PatientsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ReportsRoute: ReportsRoute,
  RobotsRoute: RobotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
