/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsRouteImport } from './routes/robots'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsIndexRouteImport } from './routes/robots.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as CampusIndexRouteImport } from './routes/campus.index'
import { Route as TagsVoiceRouteImport } from './routes/tags.voice'
import { Route as TagsSequenceRouteImport } from './routes/tags.sequence'
import { Route as TagsMotionRouteImport } from './routes/tags.motion'
import { Route as TagsKnowledgeRouteImport } from './routes/tags.knowledge'
import { Route as RobotsListRouteImport } from './routes/robots.list'
import { Route as RobotsDetailRouteImport } from './routes/robots.detail'
import { Route as RobotsCreateRouteImport } from './routes/robots.create'
import { Route as PatientsReportsRouteImport } from './routes/patients.reports'
import { Route as PatientsPrescriptionsRouteImport } from './routes/patients.prescriptions'
import { Route as PatientsPlansRouteImport } from './routes/patients.plans'
import { Route as PatientsCurrentRouteImport } from './routes/patients.current'
import { Route as PatientsBaseRouteImport } from './routes/patients.base'
import { Route as KnowledgeVoiceRouteImport } from './routes/knowledge.voice'
import { Route as KnowledgeSequenceRouteImport } from './routes/knowledge.sequence'
import { Route as KnowledgeQaRouteImport } from './routes/knowledge.qa'
import { Route as KnowledgeMotionRouteImport } from './routes/knowledge.motion'
import { Route as KnowledgeLibraryRouteImport } from './routes/knowledge.library'
import { Route as CampusMapsRouteImport } from './routes/campus.maps'
import { Route as CampusBedsRouteImport } from './routes/campus.beds'
import { Route as PatientsReportsIndexRouteImport } from './routes/patients.reports.index'
import { Route as PatientsPrescriptionsIndexRouteImport } from './routes/patients.prescriptions.index'
import { Route as PatientsPlansIndexRouteImport } from './routes/patients.plans.index'
import { Route as PatientsCurrentIndexRouteImport } from './routes/patients.current.index'
import { Route as PatientsBaseIndexRouteImport } from './routes/patients.base.index'
import { Route as KnowledgeVoiceIndexRouteImport } from './routes/knowledge.voice.index'
import { Route as KnowledgeSequenceIndexRouteImport } from './routes/knowledge.sequence.index'
import { Route as KnowledgeMotionIndexRouteImport } from './routes/knowledge.motion.index'
import { Route as KnowledgeLibraryIndexRouteImport } from './routes/knowledge.library.index'
import { Route as CampusMapsIndexRouteImport } from './routes/campus.maps.index'
import { Route as CampusBedsIndexRouteImport } from './routes/campus.beds.index'
import { Route as TagsVoiceCreateRouteImport } from './routes/tags.voice.create'
import { Route as TagsSequenceCreateRouteImport } from './routes/tags.sequence.create'
import { Route as TagsMotionCreateRouteImport } from './routes/tags.motion.create'
import { Route as TagsKnowledgeCreateRouteImport } from './routes/tags.knowledge.create'
import { Route as PatientsReportsReviewRouteImport } from './routes/patients.reports.review'
import { Route as PatientsReportsExportRouteImport } from './routes/patients.reports.export'
import { Route as PatientsPrescriptionsExportRouteImport } from './routes/patients.prescriptions.export'
import { Route as PatientsPrescriptionsEditRouteImport } from './routes/patients.prescriptions.edit'
import { Route as PatientsPrescriptionsCreateRouteImport } from './routes/patients.prescriptions.create'
import { Route as PatientsPlansExportRouteImport } from './routes/patients.plans.export'
import { Route as PatientsPlansEditRouteImport } from './routes/patients.plans.edit'
import { Route as PatientsPlansCreateRouteImport } from './routes/patients.plans.create'
import { Route as PatientsCurrentEditRouteImport } from './routes/patients.current.edit'
import { Route as PatientsCurrentCreateRouteImport } from './routes/patients.current.create'
import { Route as PatientsBaseExportRouteImport } from './routes/patients.base.export'
import { Route as PatientsBaseEditRouteImport } from './routes/patients.base.edit'
import { Route as PatientsBaseCreateRouteImport } from './routes/patients.base.create'
import { Route as PatientsPatientIdPlansRouteImport } from './routes/patients.$patientId.plans'
import { Route as KnowledgeVoiceExportRouteImport } from './routes/knowledge.voice.export'
import { Route as KnowledgeVoiceEditRouteImport } from './routes/knowledge.voice.edit'
import { Route as KnowledgeVoiceCreateRouteImport } from './routes/knowledge.voice.create'
import { Route as KnowledgeSequenceExportRouteImport } from './routes/knowledge.sequence.export'
import { Route as KnowledgeSequenceEditRouteImport } from './routes/knowledge.sequence.edit'
import { Route as KnowledgeSequenceCreateRouteImport } from './routes/knowledge.sequence.create'
import { Route as KnowledgeMotionExportRouteImport } from './routes/knowledge.motion.export'
import { Route as KnowledgeMotionEditRouteImport } from './routes/knowledge.motion.edit'
import { Route as KnowledgeMotionCreateRouteImport } from './routes/knowledge.motion.create'
import { Route as KnowledgeLibraryExportRouteImport } from './routes/knowledge.library.export'
import { Route as KnowledgeLibraryEditRouteImport } from './routes/knowledge.library.edit'
import { Route as KnowledgeLibraryCreateRouteImport } from './routes/knowledge.library.create'
import { Route as CampusMapsMapIdRouteImport } from './routes/campus.maps.$mapId'
import { Route as CampusBedsBedIdRouteImport } from './routes/campus.beds.$bedId'
import { Route as PatientsPatientIdPlansIndexRouteImport } from './routes/patients.$patientId.plans.index'
import { Route as PatientsPatientIdPlansExportRouteImport } from './routes/patients.$patientId.plans.export'
import { Route as PatientsPatientIdPlansEditRouteImport } from './routes/patients.$patientId.plans.edit'
import { Route as PatientsPatientIdPlansCreateRouteImport } from './routes/patients.$patientId.plans.create'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsIndexRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.index'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsExportRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.export'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsEditRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.edit'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsCreateRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.create'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.$prescriptionId.current'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.$prescriptionId.current.index'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.$prescriptionId.current.edit'
import { Route as PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRouteImport } from './routes/patients.$patientId.plans.$planId.prescriptions.$prescriptionId.current.create'

const RobotsRoute = RobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsIndexRoute = RobotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RobotsRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CampusIndexRoute = CampusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusRoute,
} as any)
const TagsVoiceRoute = TagsVoiceRouteImport.update({
  id: '/tags/voice',
  path: '/tags/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSequenceRoute = TagsSequenceRouteImport.update({
  id: '/tags/sequence',
  path: '/tags/sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsMotionRoute = TagsMotionRouteImport.update({
  id: '/tags/motion',
  path: '/tags/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsKnowledgeRoute = TagsKnowledgeRouteImport.update({
  id: '/tags/knowledge',
  path: '/tags/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsListRoute = RobotsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => RobotsRoute,
} as any)
const RobotsDetailRoute = RobotsDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => RobotsRoute,
} as any)
const RobotsCreateRoute = RobotsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RobotsRoute,
} as any)
const PatientsReportsRoute = PatientsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPrescriptionsRoute = PatientsPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPlansRoute = PatientsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsCurrentRoute = PatientsCurrentRouteImport.update({
  id: '/current',
  path: '/current',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsBaseRoute = PatientsBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => PatientsRoute,
} as any)
const KnowledgeVoiceRoute = KnowledgeVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSequenceRoute = KnowledgeSequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeQaRoute = KnowledgeQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeMotionRoute = KnowledgeMotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeLibraryRoute = KnowledgeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CampusMapsRoute = CampusMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => CampusRoute,
} as any)
const CampusBedsRoute = CampusBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => CampusRoute,
} as any)
const PatientsReportsIndexRoute = PatientsReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsReportsRoute,
} as any)
const PatientsPrescriptionsIndexRoute =
  PatientsPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientsPrescriptionsRoute,
  } as any)
const PatientsPlansIndexRoute = PatientsPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPlansRoute,
} as any)
const PatientsCurrentIndexRoute = PatientsCurrentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsCurrentRoute,
} as any)
const PatientsBaseIndexRoute = PatientsBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsBaseRoute,
} as any)
const KnowledgeVoiceIndexRoute = KnowledgeVoiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeVoiceRoute,
} as any)
const KnowledgeSequenceIndexRoute = KnowledgeSequenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeSequenceRoute,
} as any)
const KnowledgeMotionIndexRoute = KnowledgeMotionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeMotionRoute,
} as any)
const KnowledgeLibraryIndexRoute = KnowledgeLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeLibraryRoute,
} as any)
const CampusMapsIndexRoute = CampusMapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusMapsRoute,
} as any)
const CampusBedsIndexRoute = CampusBedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusBedsRoute,
} as any)
const TagsVoiceCreateRoute = TagsVoiceCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TagsVoiceRoute,
} as any)
const TagsSequenceCreateRoute = TagsSequenceCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TagsSequenceRoute,
} as any)
const TagsMotionCreateRoute = TagsMotionCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TagsMotionRoute,
} as any)
const TagsKnowledgeCreateRoute = TagsKnowledgeCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TagsKnowledgeRoute,
} as any)
const PatientsReportsReviewRoute = PatientsReportsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PatientsReportsRoute,
} as any)
const PatientsReportsExportRoute = PatientsReportsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => PatientsReportsRoute,
} as any)
const PatientsPrescriptionsExportRoute =
  PatientsPrescriptionsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => PatientsPrescriptionsRoute,
  } as any)
const PatientsPrescriptionsEditRoute =
  PatientsPrescriptionsEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PatientsPrescriptionsRoute,
  } as any)
const PatientsPrescriptionsCreateRoute =
  PatientsPrescriptionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PatientsPrescriptionsRoute,
  } as any)
const PatientsPlansExportRoute = PatientsPlansExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => PatientsPlansRoute,
} as any)
const PatientsPlansEditRoute = PatientsPlansEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PatientsPlansRoute,
} as any)
const PatientsPlansCreateRoute = PatientsPlansCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PatientsPlansRoute,
} as any)
const PatientsCurrentEditRoute = PatientsCurrentEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PatientsCurrentRoute,
} as any)
const PatientsCurrentCreateRoute = PatientsCurrentCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PatientsCurrentRoute,
} as any)
const PatientsBaseExportRoute = PatientsBaseExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => PatientsBaseRoute,
} as any)
const PatientsBaseEditRoute = PatientsBaseEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PatientsBaseRoute,
} as any)
const PatientsBaseCreateRoute = PatientsBaseCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PatientsBaseRoute,
} as any)
const PatientsPatientIdPlansRoute = PatientsPatientIdPlansRouteImport.update({
  id: '/$patientId/plans',
  path: '/$patientId/plans',
  getParentRoute: () => PatientsRoute,
} as any)
const KnowledgeVoiceExportRoute = KnowledgeVoiceExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => KnowledgeVoiceRoute,
} as any)
const KnowledgeVoiceEditRoute = KnowledgeVoiceEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => KnowledgeVoiceRoute,
} as any)
const KnowledgeVoiceCreateRoute = KnowledgeVoiceCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeVoiceRoute,
} as any)
const KnowledgeSequenceExportRoute = KnowledgeSequenceExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => KnowledgeSequenceRoute,
} as any)
const KnowledgeSequenceEditRoute = KnowledgeSequenceEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => KnowledgeSequenceRoute,
} as any)
const KnowledgeSequenceCreateRoute = KnowledgeSequenceCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeSequenceRoute,
} as any)
const KnowledgeMotionExportRoute = KnowledgeMotionExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => KnowledgeMotionRoute,
} as any)
const KnowledgeMotionEditRoute = KnowledgeMotionEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => KnowledgeMotionRoute,
} as any)
const KnowledgeMotionCreateRoute = KnowledgeMotionCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeMotionRoute,
} as any)
const KnowledgeLibraryExportRoute = KnowledgeLibraryExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => KnowledgeLibraryRoute,
} as any)
const KnowledgeLibraryEditRoute = KnowledgeLibraryEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => KnowledgeLibraryRoute,
} as any)
const KnowledgeLibraryCreateRoute = KnowledgeLibraryCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeLibraryRoute,
} as any)
const CampusMapsMapIdRoute = CampusMapsMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => CampusMapsRoute,
} as any)
const CampusBedsBedIdRoute = CampusBedsBedIdRouteImport.update({
  id: '/$bedId',
  path: '/$bedId',
  getParentRoute: () => CampusBedsRoute,
} as any)
const PatientsPatientIdPlansIndexRoute =
  PatientsPatientIdPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientsPatientIdPlansRoute,
  } as any)
const PatientsPatientIdPlansExportRoute =
  PatientsPatientIdPlansExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => PatientsPatientIdPlansRoute,
  } as any)
const PatientsPatientIdPlansEditRoute =
  PatientsPatientIdPlansEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PatientsPatientIdPlansRoute,
  } as any)
const PatientsPatientIdPlansCreateRoute =
  PatientsPatientIdPlansCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PatientsPatientIdPlansRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsRouteImport.update({
    id: '/$planId/prescriptions',
    path: '/$planId/prescriptions',
    getParentRoute: () => PatientsPatientIdPlansRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientsPatientIdPlansPlanIdPrescriptionsRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsExportRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => PatientsPatientIdPlansPlanIdPrescriptionsRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsEditRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PatientsPatientIdPlansPlanIdPrescriptionsRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PatientsPatientIdPlansPlanIdPrescriptionsRoute,
  } as any)
const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteImport.update(
    {
      id: '/$prescriptionId/current',
      path: '/$prescriptionId/current',
      getParentRoute: () => PatientsPatientIdPlansPlanIdPrescriptionsRoute,
    } as any,
  )
const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute,
    } as any,
  )
const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute,
    } as any,
  )
const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute =
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRouteImport.update(
    {
      id: '/create',
      path: '/create',
      getParentRoute: () =>
        PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/patients': typeof PatientsRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/robots': typeof RobotsRouteWithChildren
  '/campus/beds': typeof CampusBedsRouteWithChildren
  '/campus/maps': typeof CampusMapsRouteWithChildren
  '/knowledge/library': typeof KnowledgeLibraryRouteWithChildren
  '/knowledge/motion': typeof KnowledgeMotionRouteWithChildren
  '/knowledge/qa': typeof KnowledgeQaRoute
  '/knowledge/sequence': typeof KnowledgeSequenceRouteWithChildren
  '/knowledge/voice': typeof KnowledgeVoiceRouteWithChildren
  '/patients/base': typeof PatientsBaseRouteWithChildren
  '/patients/current': typeof PatientsCurrentRouteWithChildren
  '/patients/plans': typeof PatientsPlansRouteWithChildren
  '/patients/prescriptions': typeof PatientsPrescriptionsRouteWithChildren
  '/patients/reports': typeof PatientsReportsRouteWithChildren
  '/robots/create': typeof RobotsCreateRoute
  '/robots/detail': typeof RobotsDetailRoute
  '/robots/list': typeof RobotsListRoute
  '/tags/knowledge': typeof TagsKnowledgeRouteWithChildren
  '/tags/motion': typeof TagsMotionRouteWithChildren
  '/tags/sequence': typeof TagsSequenceRouteWithChildren
  '/tags/voice': typeof TagsVoiceRouteWithChildren
  '/campus/': typeof CampusIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/robots/': typeof RobotsIndexRoute
  '/campus/beds/$bedId': typeof CampusBedsBedIdRoute
  '/campus/maps/$mapId': typeof CampusMapsMapIdRoute
  '/knowledge/library/create': typeof KnowledgeLibraryCreateRoute
  '/knowledge/library/edit': typeof KnowledgeLibraryEditRoute
  '/knowledge/library/export': typeof KnowledgeLibraryExportRoute
  '/knowledge/motion/create': typeof KnowledgeMotionCreateRoute
  '/knowledge/motion/edit': typeof KnowledgeMotionEditRoute
  '/knowledge/motion/export': typeof KnowledgeMotionExportRoute
  '/knowledge/sequence/create': typeof KnowledgeSequenceCreateRoute
  '/knowledge/sequence/edit': typeof KnowledgeSequenceEditRoute
  '/knowledge/sequence/export': typeof KnowledgeSequenceExportRoute
  '/knowledge/voice/create': typeof KnowledgeVoiceCreateRoute
  '/knowledge/voice/edit': typeof KnowledgeVoiceEditRoute
  '/knowledge/voice/export': typeof KnowledgeVoiceExportRoute
  '/patients/$patientId/plans': typeof PatientsPatientIdPlansRouteWithChildren
  '/patients/base/create': typeof PatientsBaseCreateRoute
  '/patients/base/edit': typeof PatientsBaseEditRoute
  '/patients/base/export': typeof PatientsBaseExportRoute
  '/patients/current/create': typeof PatientsCurrentCreateRoute
  '/patients/current/edit': typeof PatientsCurrentEditRoute
  '/patients/plans/create': typeof PatientsPlansCreateRoute
  '/patients/plans/edit': typeof PatientsPlansEditRoute
  '/patients/plans/export': typeof PatientsPlansExportRoute
  '/patients/prescriptions/create': typeof PatientsPrescriptionsCreateRoute
  '/patients/prescriptions/edit': typeof PatientsPrescriptionsEditRoute
  '/patients/prescriptions/export': typeof PatientsPrescriptionsExportRoute
  '/patients/reports/export': typeof PatientsReportsExportRoute
  '/patients/reports/review': typeof PatientsReportsReviewRoute
  '/tags/knowledge/create': typeof TagsKnowledgeCreateRoute
  '/tags/motion/create': typeof TagsMotionCreateRoute
  '/tags/sequence/create': typeof TagsSequenceCreateRoute
  '/tags/voice/create': typeof TagsVoiceCreateRoute
  '/campus/beds/': typeof CampusBedsIndexRoute
  '/campus/maps/': typeof CampusMapsIndexRoute
  '/knowledge/library/': typeof KnowledgeLibraryIndexRoute
  '/knowledge/motion/': typeof KnowledgeMotionIndexRoute
  '/knowledge/sequence/': typeof KnowledgeSequenceIndexRoute
  '/knowledge/voice/': typeof KnowledgeVoiceIndexRoute
  '/patients/base/': typeof PatientsBaseIndexRoute
  '/patients/current/': typeof PatientsCurrentIndexRoute
  '/patients/plans/': typeof PatientsPlansIndexRoute
  '/patients/prescriptions/': typeof PatientsPrescriptionsIndexRoute
  '/patients/reports/': typeof PatientsReportsIndexRoute
  '/patients/$patientId/plans/create': typeof PatientsPatientIdPlansCreateRoute
  '/patients/$patientId/plans/edit': typeof PatientsPatientIdPlansEditRoute
  '/patients/$patientId/plans/export': typeof PatientsPatientIdPlansExportRoute
  '/patients/$patientId/plans/': typeof PatientsPatientIdPlansIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions': typeof PatientsPatientIdPlansPlanIdPrescriptionsRouteWithChildren
  '/patients/$patientId/plans/$planId/prescriptions/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/export': typeof PatientsPatientIdPlansPlanIdPrescriptionsExportRoute
  '/patients/$patientId/plans/$planId/prescriptions/': typeof PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteWithChildren
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/knowledge/qa': typeof KnowledgeQaRoute
  '/robots/create': typeof RobotsCreateRoute
  '/robots/detail': typeof RobotsDetailRoute
  '/robots/list': typeof RobotsListRoute
  '/tags/knowledge': typeof TagsKnowledgeRouteWithChildren
  '/tags/motion': typeof TagsMotionRouteWithChildren
  '/tags/sequence': typeof TagsSequenceRouteWithChildren
  '/tags/voice': typeof TagsVoiceRouteWithChildren
  '/campus': typeof CampusIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/robots': typeof RobotsIndexRoute
  '/campus/beds/$bedId': typeof CampusBedsBedIdRoute
  '/campus/maps/$mapId': typeof CampusMapsMapIdRoute
  '/knowledge/library/create': typeof KnowledgeLibraryCreateRoute
  '/knowledge/library/edit': typeof KnowledgeLibraryEditRoute
  '/knowledge/library/export': typeof KnowledgeLibraryExportRoute
  '/knowledge/motion/create': typeof KnowledgeMotionCreateRoute
  '/knowledge/motion/edit': typeof KnowledgeMotionEditRoute
  '/knowledge/motion/export': typeof KnowledgeMotionExportRoute
  '/knowledge/sequence/create': typeof KnowledgeSequenceCreateRoute
  '/knowledge/sequence/edit': typeof KnowledgeSequenceEditRoute
  '/knowledge/sequence/export': typeof KnowledgeSequenceExportRoute
  '/knowledge/voice/create': typeof KnowledgeVoiceCreateRoute
  '/knowledge/voice/edit': typeof KnowledgeVoiceEditRoute
  '/knowledge/voice/export': typeof KnowledgeVoiceExportRoute
  '/patients/base/create': typeof PatientsBaseCreateRoute
  '/patients/base/edit': typeof PatientsBaseEditRoute
  '/patients/base/export': typeof PatientsBaseExportRoute
  '/patients/current/create': typeof PatientsCurrentCreateRoute
  '/patients/current/edit': typeof PatientsCurrentEditRoute
  '/patients/plans/create': typeof PatientsPlansCreateRoute
  '/patients/plans/edit': typeof PatientsPlansEditRoute
  '/patients/plans/export': typeof PatientsPlansExportRoute
  '/patients/prescriptions/create': typeof PatientsPrescriptionsCreateRoute
  '/patients/prescriptions/edit': typeof PatientsPrescriptionsEditRoute
  '/patients/prescriptions/export': typeof PatientsPrescriptionsExportRoute
  '/patients/reports/export': typeof PatientsReportsExportRoute
  '/patients/reports/review': typeof PatientsReportsReviewRoute
  '/tags/knowledge/create': typeof TagsKnowledgeCreateRoute
  '/tags/motion/create': typeof TagsMotionCreateRoute
  '/tags/sequence/create': typeof TagsSequenceCreateRoute
  '/tags/voice/create': typeof TagsVoiceCreateRoute
  '/campus/beds': typeof CampusBedsIndexRoute
  '/campus/maps': typeof CampusMapsIndexRoute
  '/knowledge/library': typeof KnowledgeLibraryIndexRoute
  '/knowledge/motion': typeof KnowledgeMotionIndexRoute
  '/knowledge/sequence': typeof KnowledgeSequenceIndexRoute
  '/knowledge/voice': typeof KnowledgeVoiceIndexRoute
  '/patients/base': typeof PatientsBaseIndexRoute
  '/patients/current': typeof PatientsCurrentIndexRoute
  '/patients/plans': typeof PatientsPlansIndexRoute
  '/patients/prescriptions': typeof PatientsPrescriptionsIndexRoute
  '/patients/reports': typeof PatientsReportsIndexRoute
  '/patients/$patientId/plans/create': typeof PatientsPatientIdPlansCreateRoute
  '/patients/$patientId/plans/edit': typeof PatientsPatientIdPlansEditRoute
  '/patients/$patientId/plans/export': typeof PatientsPatientIdPlansExportRoute
  '/patients/$patientId/plans': typeof PatientsPatientIdPlansIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/export': typeof PatientsPatientIdPlansPlanIdPrescriptionsExportRoute
  '/patients/$patientId/plans/$planId/prescriptions': typeof PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/patients': typeof PatientsRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/robots': typeof RobotsRouteWithChildren
  '/campus/beds': typeof CampusBedsRouteWithChildren
  '/campus/maps': typeof CampusMapsRouteWithChildren
  '/knowledge/library': typeof KnowledgeLibraryRouteWithChildren
  '/knowledge/motion': typeof KnowledgeMotionRouteWithChildren
  '/knowledge/qa': typeof KnowledgeQaRoute
  '/knowledge/sequence': typeof KnowledgeSequenceRouteWithChildren
  '/knowledge/voice': typeof KnowledgeVoiceRouteWithChildren
  '/patients/base': typeof PatientsBaseRouteWithChildren
  '/patients/current': typeof PatientsCurrentRouteWithChildren
  '/patients/plans': typeof PatientsPlansRouteWithChildren
  '/patients/prescriptions': typeof PatientsPrescriptionsRouteWithChildren
  '/patients/reports': typeof PatientsReportsRouteWithChildren
  '/robots/create': typeof RobotsCreateRoute
  '/robots/detail': typeof RobotsDetailRoute
  '/robots/list': typeof RobotsListRoute
  '/tags/knowledge': typeof TagsKnowledgeRouteWithChildren
  '/tags/motion': typeof TagsMotionRouteWithChildren
  '/tags/sequence': typeof TagsSequenceRouteWithChildren
  '/tags/voice': typeof TagsVoiceRouteWithChildren
  '/campus/': typeof CampusIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/robots/': typeof RobotsIndexRoute
  '/campus/beds/$bedId': typeof CampusBedsBedIdRoute
  '/campus/maps/$mapId': typeof CampusMapsMapIdRoute
  '/knowledge/library/create': typeof KnowledgeLibraryCreateRoute
  '/knowledge/library/edit': typeof KnowledgeLibraryEditRoute
  '/knowledge/library/export': typeof KnowledgeLibraryExportRoute
  '/knowledge/motion/create': typeof KnowledgeMotionCreateRoute
  '/knowledge/motion/edit': typeof KnowledgeMotionEditRoute
  '/knowledge/motion/export': typeof KnowledgeMotionExportRoute
  '/knowledge/sequence/create': typeof KnowledgeSequenceCreateRoute
  '/knowledge/sequence/edit': typeof KnowledgeSequenceEditRoute
  '/knowledge/sequence/export': typeof KnowledgeSequenceExportRoute
  '/knowledge/voice/create': typeof KnowledgeVoiceCreateRoute
  '/knowledge/voice/edit': typeof KnowledgeVoiceEditRoute
  '/knowledge/voice/export': typeof KnowledgeVoiceExportRoute
  '/patients/$patientId/plans': typeof PatientsPatientIdPlansRouteWithChildren
  '/patients/base/create': typeof PatientsBaseCreateRoute
  '/patients/base/edit': typeof PatientsBaseEditRoute
  '/patients/base/export': typeof PatientsBaseExportRoute
  '/patients/current/create': typeof PatientsCurrentCreateRoute
  '/patients/current/edit': typeof PatientsCurrentEditRoute
  '/patients/plans/create': typeof PatientsPlansCreateRoute
  '/patients/plans/edit': typeof PatientsPlansEditRoute
  '/patients/plans/export': typeof PatientsPlansExportRoute
  '/patients/prescriptions/create': typeof PatientsPrescriptionsCreateRoute
  '/patients/prescriptions/edit': typeof PatientsPrescriptionsEditRoute
  '/patients/prescriptions/export': typeof PatientsPrescriptionsExportRoute
  '/patients/reports/export': typeof PatientsReportsExportRoute
  '/patients/reports/review': typeof PatientsReportsReviewRoute
  '/tags/knowledge/create': typeof TagsKnowledgeCreateRoute
  '/tags/motion/create': typeof TagsMotionCreateRoute
  '/tags/sequence/create': typeof TagsSequenceCreateRoute
  '/tags/voice/create': typeof TagsVoiceCreateRoute
  '/campus/beds/': typeof CampusBedsIndexRoute
  '/campus/maps/': typeof CampusMapsIndexRoute
  '/knowledge/library/': typeof KnowledgeLibraryIndexRoute
  '/knowledge/motion/': typeof KnowledgeMotionIndexRoute
  '/knowledge/sequence/': typeof KnowledgeSequenceIndexRoute
  '/knowledge/voice/': typeof KnowledgeVoiceIndexRoute
  '/patients/base/': typeof PatientsBaseIndexRoute
  '/patients/current/': typeof PatientsCurrentIndexRoute
  '/patients/plans/': typeof PatientsPlansIndexRoute
  '/patients/prescriptions/': typeof PatientsPrescriptionsIndexRoute
  '/patients/reports/': typeof PatientsReportsIndexRoute
  '/patients/$patientId/plans/create': typeof PatientsPatientIdPlansCreateRoute
  '/patients/$patientId/plans/edit': typeof PatientsPatientIdPlansEditRoute
  '/patients/$patientId/plans/export': typeof PatientsPatientIdPlansExportRoute
  '/patients/$patientId/plans/': typeof PatientsPatientIdPlansIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions': typeof PatientsPatientIdPlansPlanIdPrescriptionsRouteWithChildren
  '/patients/$patientId/plans/$planId/prescriptions/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/export': typeof PatientsPatientIdPlansPlanIdPrescriptionsExportRoute
  '/patients/$patientId/plans/$planId/prescriptions/': typeof PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteWithChildren
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute
  '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/': typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campus'
    | '/knowledge'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/robots'
    | '/campus/beds'
    | '/campus/maps'
    | '/knowledge/library'
    | '/knowledge/motion'
    | '/knowledge/qa'
    | '/knowledge/sequence'
    | '/knowledge/voice'
    | '/patients/base'
    | '/patients/current'
    | '/patients/plans'
    | '/patients/prescriptions'
    | '/patients/reports'
    | '/robots/create'
    | '/robots/detail'
    | '/robots/list'
    | '/tags/knowledge'
    | '/tags/motion'
    | '/tags/sequence'
    | '/tags/voice'
    | '/campus/'
    | '/knowledge/'
    | '/patients/'
    | '/robots/'
    | '/campus/beds/$bedId'
    | '/campus/maps/$mapId'
    | '/knowledge/library/create'
    | '/knowledge/library/edit'
    | '/knowledge/library/export'
    | '/knowledge/motion/create'
    | '/knowledge/motion/edit'
    | '/knowledge/motion/export'
    | '/knowledge/sequence/create'
    | '/knowledge/sequence/edit'
    | '/knowledge/sequence/export'
    | '/knowledge/voice/create'
    | '/knowledge/voice/edit'
    | '/knowledge/voice/export'
    | '/patients/$patientId/plans'
    | '/patients/base/create'
    | '/patients/base/edit'
    | '/patients/base/export'
    | '/patients/current/create'
    | '/patients/current/edit'
    | '/patients/plans/create'
    | '/patients/plans/edit'
    | '/patients/plans/export'
    | '/patients/prescriptions/create'
    | '/patients/prescriptions/edit'
    | '/patients/prescriptions/export'
    | '/patients/reports/export'
    | '/patients/reports/review'
    | '/tags/knowledge/create'
    | '/tags/motion/create'
    | '/tags/sequence/create'
    | '/tags/voice/create'
    | '/campus/beds/'
    | '/campus/maps/'
    | '/knowledge/library/'
    | '/knowledge/motion/'
    | '/knowledge/sequence/'
    | '/knowledge/voice/'
    | '/patients/base/'
    | '/patients/current/'
    | '/patients/plans/'
    | '/patients/prescriptions/'
    | '/patients/reports/'
    | '/patients/$patientId/plans/create'
    | '/patients/$patientId/plans/edit'
    | '/patients/$patientId/plans/export'
    | '/patients/$patientId/plans/'
    | '/patients/$patientId/plans/$planId/prescriptions'
    | '/patients/$patientId/plans/$planId/prescriptions/create'
    | '/patients/$patientId/plans/$planId/prescriptions/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/export'
    | '/patients/$patientId/plans/$planId/prescriptions/'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prescriptions'
    | '/reports'
    | '/knowledge/qa'
    | '/robots/create'
    | '/robots/detail'
    | '/robots/list'
    | '/tags/knowledge'
    | '/tags/motion'
    | '/tags/sequence'
    | '/tags/voice'
    | '/campus'
    | '/knowledge'
    | '/patients'
    | '/robots'
    | '/campus/beds/$bedId'
    | '/campus/maps/$mapId'
    | '/knowledge/library/create'
    | '/knowledge/library/edit'
    | '/knowledge/library/export'
    | '/knowledge/motion/create'
    | '/knowledge/motion/edit'
    | '/knowledge/motion/export'
    | '/knowledge/sequence/create'
    | '/knowledge/sequence/edit'
    | '/knowledge/sequence/export'
    | '/knowledge/voice/create'
    | '/knowledge/voice/edit'
    | '/knowledge/voice/export'
    | '/patients/base/create'
    | '/patients/base/edit'
    | '/patients/base/export'
    | '/patients/current/create'
    | '/patients/current/edit'
    | '/patients/plans/create'
    | '/patients/plans/edit'
    | '/patients/plans/export'
    | '/patients/prescriptions/create'
    | '/patients/prescriptions/edit'
    | '/patients/prescriptions/export'
    | '/patients/reports/export'
    | '/patients/reports/review'
    | '/tags/knowledge/create'
    | '/tags/motion/create'
    | '/tags/sequence/create'
    | '/tags/voice/create'
    | '/campus/beds'
    | '/campus/maps'
    | '/knowledge/library'
    | '/knowledge/motion'
    | '/knowledge/sequence'
    | '/knowledge/voice'
    | '/patients/base'
    | '/patients/current'
    | '/patients/plans'
    | '/patients/prescriptions'
    | '/patients/reports'
    | '/patients/$patientId/plans/create'
    | '/patients/$patientId/plans/edit'
    | '/patients/$patientId/plans/export'
    | '/patients/$patientId/plans'
    | '/patients/$patientId/plans/$planId/prescriptions/create'
    | '/patients/$patientId/plans/$planId/prescriptions/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/export'
    | '/patients/$patientId/plans/$planId/prescriptions'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current'
  id:
    | '__root__'
    | '/'
    | '/campus'
    | '/knowledge'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/robots'
    | '/campus/beds'
    | '/campus/maps'
    | '/knowledge/library'
    | '/knowledge/motion'
    | '/knowledge/qa'
    | '/knowledge/sequence'
    | '/knowledge/voice'
    | '/patients/base'
    | '/patients/current'
    | '/patients/plans'
    | '/patients/prescriptions'
    | '/patients/reports'
    | '/robots/create'
    | '/robots/detail'
    | '/robots/list'
    | '/tags/knowledge'
    | '/tags/motion'
    | '/tags/sequence'
    | '/tags/voice'
    | '/campus/'
    | '/knowledge/'
    | '/patients/'
    | '/robots/'
    | '/campus/beds/$bedId'
    | '/campus/maps/$mapId'
    | '/knowledge/library/create'
    | '/knowledge/library/edit'
    | '/knowledge/library/export'
    | '/knowledge/motion/create'
    | '/knowledge/motion/edit'
    | '/knowledge/motion/export'
    | '/knowledge/sequence/create'
    | '/knowledge/sequence/edit'
    | '/knowledge/sequence/export'
    | '/knowledge/voice/create'
    | '/knowledge/voice/edit'
    | '/knowledge/voice/export'
    | '/patients/$patientId/plans'
    | '/patients/base/create'
    | '/patients/base/edit'
    | '/patients/base/export'
    | '/patients/current/create'
    | '/patients/current/edit'
    | '/patients/plans/create'
    | '/patients/plans/edit'
    | '/patients/plans/export'
    | '/patients/prescriptions/create'
    | '/patients/prescriptions/edit'
    | '/patients/prescriptions/export'
    | '/patients/reports/export'
    | '/patients/reports/review'
    | '/tags/knowledge/create'
    | '/tags/motion/create'
    | '/tags/sequence/create'
    | '/tags/voice/create'
    | '/campus/beds/'
    | '/campus/maps/'
    | '/knowledge/library/'
    | '/knowledge/motion/'
    | '/knowledge/sequence/'
    | '/knowledge/voice/'
    | '/patients/base/'
    | '/patients/current/'
    | '/patients/plans/'
    | '/patients/prescriptions/'
    | '/patients/reports/'
    | '/patients/$patientId/plans/create'
    | '/patients/$patientId/plans/edit'
    | '/patients/$patientId/plans/export'
    | '/patients/$patientId/plans/'
    | '/patients/$patientId/plans/$planId/prescriptions'
    | '/patients/$patientId/plans/$planId/prescriptions/create'
    | '/patients/$patientId/plans/$planId/prescriptions/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/export'
    | '/patients/$patientId/plans/$planId/prescriptions/'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit'
    | '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PatientsRoute: typeof PatientsRouteWithChildren
  PrescriptionsRoute: typeof PrescriptionsRoute
  ReportsRoute: typeof ReportsRoute
  RobotsRoute: typeof RobotsRouteWithChildren
  TagsKnowledgeRoute: typeof TagsKnowledgeRouteWithChildren
  TagsMotionRoute: typeof TagsMotionRouteWithChildren
  TagsSequenceRoute: typeof TagsSequenceRouteWithChildren
  TagsVoiceRoute: typeof TagsVoiceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots': {
      id: '/robots'
      path: '/robots'
      fullPath: '/robots'
      preLoaderRoute: typeof RobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/': {
      id: '/robots/'
      path: '/'
      fullPath: '/robots/'
      preLoaderRoute: typeof RobotsIndexRouteImport
      parentRoute: typeof RobotsRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/campus/': {
      id: '/campus/'
      path: '/'
      fullPath: '/campus/'
      preLoaderRoute: typeof CampusIndexRouteImport
      parentRoute: typeof CampusRoute
    }
    '/tags/voice': {
      id: '/tags/voice'
      path: '/tags/voice'
      fullPath: '/tags/voice'
      preLoaderRoute: typeof TagsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/sequence': {
      id: '/tags/sequence'
      path: '/tags/sequence'
      fullPath: '/tags/sequence'
      preLoaderRoute: typeof TagsSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/motion': {
      id: '/tags/motion'
      path: '/tags/motion'
      fullPath: '/tags/motion'
      preLoaderRoute: typeof TagsMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/knowledge': {
      id: '/tags/knowledge'
      path: '/tags/knowledge'
      fullPath: '/tags/knowledge'
      preLoaderRoute: typeof TagsKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/list': {
      id: '/robots/list'
      path: '/list'
      fullPath: '/robots/list'
      preLoaderRoute: typeof RobotsListRouteImport
      parentRoute: typeof RobotsRoute
    }
    '/robots/detail': {
      id: '/robots/detail'
      path: '/detail'
      fullPath: '/robots/detail'
      preLoaderRoute: typeof RobotsDetailRouteImport
      parentRoute: typeof RobotsRoute
    }
    '/robots/create': {
      id: '/robots/create'
      path: '/create'
      fullPath: '/robots/create'
      preLoaderRoute: typeof RobotsCreateRouteImport
      parentRoute: typeof RobotsRoute
    }
    '/patients/reports': {
      id: '/patients/reports'
      path: '/reports'
      fullPath: '/patients/reports'
      preLoaderRoute: typeof PatientsReportsRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/prescriptions': {
      id: '/patients/prescriptions'
      path: '/prescriptions'
      fullPath: '/patients/prescriptions'
      preLoaderRoute: typeof PatientsPrescriptionsRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/plans': {
      id: '/patients/plans'
      path: '/plans'
      fullPath: '/patients/plans'
      preLoaderRoute: typeof PatientsPlansRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/current': {
      id: '/patients/current'
      path: '/current'
      fullPath: '/patients/current'
      preLoaderRoute: typeof PatientsCurrentRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/base': {
      id: '/patients/base'
      path: '/base'
      fullPath: '/patients/base'
      preLoaderRoute: typeof PatientsBaseRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/knowledge/voice': {
      id: '/knowledge/voice'
      path: '/voice'
      fullPath: '/knowledge/voice'
      preLoaderRoute: typeof KnowledgeVoiceRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/sequence': {
      id: '/knowledge/sequence'
      path: '/sequence'
      fullPath: '/knowledge/sequence'
      preLoaderRoute: typeof KnowledgeSequenceRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/qa': {
      id: '/knowledge/qa'
      path: '/qa'
      fullPath: '/knowledge/qa'
      preLoaderRoute: typeof KnowledgeQaRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/motion': {
      id: '/knowledge/motion'
      path: '/motion'
      fullPath: '/knowledge/motion'
      preLoaderRoute: typeof KnowledgeMotionRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/library': {
      id: '/knowledge/library'
      path: '/library'
      fullPath: '/knowledge/library'
      preLoaderRoute: typeof KnowledgeLibraryRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/campus/maps': {
      id: '/campus/maps'
      path: '/maps'
      fullPath: '/campus/maps'
      preLoaderRoute: typeof CampusMapsRouteImport
      parentRoute: typeof CampusRoute
    }
    '/campus/beds': {
      id: '/campus/beds'
      path: '/beds'
      fullPath: '/campus/beds'
      preLoaderRoute: typeof CampusBedsRouteImport
      parentRoute: typeof CampusRoute
    }
    '/patients/reports/': {
      id: '/patients/reports/'
      path: '/'
      fullPath: '/patients/reports/'
      preLoaderRoute: typeof PatientsReportsIndexRouteImport
      parentRoute: typeof PatientsReportsRoute
    }
    '/patients/prescriptions/': {
      id: '/patients/prescriptions/'
      path: '/'
      fullPath: '/patients/prescriptions/'
      preLoaderRoute: typeof PatientsPrescriptionsIndexRouteImport
      parentRoute: typeof PatientsPrescriptionsRoute
    }
    '/patients/plans/': {
      id: '/patients/plans/'
      path: '/'
      fullPath: '/patients/plans/'
      preLoaderRoute: typeof PatientsPlansIndexRouteImport
      parentRoute: typeof PatientsPlansRoute
    }
    '/patients/current/': {
      id: '/patients/current/'
      path: '/'
      fullPath: '/patients/current/'
      preLoaderRoute: typeof PatientsCurrentIndexRouteImport
      parentRoute: typeof PatientsCurrentRoute
    }
    '/patients/base/': {
      id: '/patients/base/'
      path: '/'
      fullPath: '/patients/base/'
      preLoaderRoute: typeof PatientsBaseIndexRouteImport
      parentRoute: typeof PatientsBaseRoute
    }
    '/knowledge/voice/': {
      id: '/knowledge/voice/'
      path: '/'
      fullPath: '/knowledge/voice/'
      preLoaderRoute: typeof KnowledgeVoiceIndexRouteImport
      parentRoute: typeof KnowledgeVoiceRoute
    }
    '/knowledge/sequence/': {
      id: '/knowledge/sequence/'
      path: '/'
      fullPath: '/knowledge/sequence/'
      preLoaderRoute: typeof KnowledgeSequenceIndexRouteImport
      parentRoute: typeof KnowledgeSequenceRoute
    }
    '/knowledge/motion/': {
      id: '/knowledge/motion/'
      path: '/'
      fullPath: '/knowledge/motion/'
      preLoaderRoute: typeof KnowledgeMotionIndexRouteImport
      parentRoute: typeof KnowledgeMotionRoute
    }
    '/knowledge/library/': {
      id: '/knowledge/library/'
      path: '/'
      fullPath: '/knowledge/library/'
      preLoaderRoute: typeof KnowledgeLibraryIndexRouteImport
      parentRoute: typeof KnowledgeLibraryRoute
    }
    '/campus/maps/': {
      id: '/campus/maps/'
      path: '/'
      fullPath: '/campus/maps/'
      preLoaderRoute: typeof CampusMapsIndexRouteImport
      parentRoute: typeof CampusMapsRoute
    }
    '/campus/beds/': {
      id: '/campus/beds/'
      path: '/'
      fullPath: '/campus/beds/'
      preLoaderRoute: typeof CampusBedsIndexRouteImport
      parentRoute: typeof CampusBedsRoute
    }
    '/tags/voice/create': {
      id: '/tags/voice/create'
      path: '/create'
      fullPath: '/tags/voice/create'
      preLoaderRoute: typeof TagsVoiceCreateRouteImport
      parentRoute: typeof TagsVoiceRoute
    }
    '/tags/sequence/create': {
      id: '/tags/sequence/create'
      path: '/create'
      fullPath: '/tags/sequence/create'
      preLoaderRoute: typeof TagsSequenceCreateRouteImport
      parentRoute: typeof TagsSequenceRoute
    }
    '/tags/motion/create': {
      id: '/tags/motion/create'
      path: '/create'
      fullPath: '/tags/motion/create'
      preLoaderRoute: typeof TagsMotionCreateRouteImport
      parentRoute: typeof TagsMotionRoute
    }
    '/tags/knowledge/create': {
      id: '/tags/knowledge/create'
      path: '/create'
      fullPath: '/tags/knowledge/create'
      preLoaderRoute: typeof TagsKnowledgeCreateRouteImport
      parentRoute: typeof TagsKnowledgeRoute
    }
    '/patients/reports/review': {
      id: '/patients/reports/review'
      path: '/review'
      fullPath: '/patients/reports/review'
      preLoaderRoute: typeof PatientsReportsReviewRouteImport
      parentRoute: typeof PatientsReportsRoute
    }
    '/patients/reports/export': {
      id: '/patients/reports/export'
      path: '/export'
      fullPath: '/patients/reports/export'
      preLoaderRoute: typeof PatientsReportsExportRouteImport
      parentRoute: typeof PatientsReportsRoute
    }
    '/patients/prescriptions/export': {
      id: '/patients/prescriptions/export'
      path: '/export'
      fullPath: '/patients/prescriptions/export'
      preLoaderRoute: typeof PatientsPrescriptionsExportRouteImport
      parentRoute: typeof PatientsPrescriptionsRoute
    }
    '/patients/prescriptions/edit': {
      id: '/patients/prescriptions/edit'
      path: '/edit'
      fullPath: '/patients/prescriptions/edit'
      preLoaderRoute: typeof PatientsPrescriptionsEditRouteImport
      parentRoute: typeof PatientsPrescriptionsRoute
    }
    '/patients/prescriptions/create': {
      id: '/patients/prescriptions/create'
      path: '/create'
      fullPath: '/patients/prescriptions/create'
      preLoaderRoute: typeof PatientsPrescriptionsCreateRouteImport
      parentRoute: typeof PatientsPrescriptionsRoute
    }
    '/patients/plans/export': {
      id: '/patients/plans/export'
      path: '/export'
      fullPath: '/patients/plans/export'
      preLoaderRoute: typeof PatientsPlansExportRouteImport
      parentRoute: typeof PatientsPlansRoute
    }
    '/patients/plans/edit': {
      id: '/patients/plans/edit'
      path: '/edit'
      fullPath: '/patients/plans/edit'
      preLoaderRoute: typeof PatientsPlansEditRouteImport
      parentRoute: typeof PatientsPlansRoute
    }
    '/patients/plans/create': {
      id: '/patients/plans/create'
      path: '/create'
      fullPath: '/patients/plans/create'
      preLoaderRoute: typeof PatientsPlansCreateRouteImport
      parentRoute: typeof PatientsPlansRoute
    }
    '/patients/current/edit': {
      id: '/patients/current/edit'
      path: '/edit'
      fullPath: '/patients/current/edit'
      preLoaderRoute: typeof PatientsCurrentEditRouteImport
      parentRoute: typeof PatientsCurrentRoute
    }
    '/patients/current/create': {
      id: '/patients/current/create'
      path: '/create'
      fullPath: '/patients/current/create'
      preLoaderRoute: typeof PatientsCurrentCreateRouteImport
      parentRoute: typeof PatientsCurrentRoute
    }
    '/patients/base/export': {
      id: '/patients/base/export'
      path: '/export'
      fullPath: '/patients/base/export'
      preLoaderRoute: typeof PatientsBaseExportRouteImport
      parentRoute: typeof PatientsBaseRoute
    }
    '/patients/base/edit': {
      id: '/patients/base/edit'
      path: '/edit'
      fullPath: '/patients/base/edit'
      preLoaderRoute: typeof PatientsBaseEditRouteImport
      parentRoute: typeof PatientsBaseRoute
    }
    '/patients/base/create': {
      id: '/patients/base/create'
      path: '/create'
      fullPath: '/patients/base/create'
      preLoaderRoute: typeof PatientsBaseCreateRouteImport
      parentRoute: typeof PatientsBaseRoute
    }
    '/patients/$patientId/plans': {
      id: '/patients/$patientId/plans'
      path: '/$patientId/plans'
      fullPath: '/patients/$patientId/plans'
      preLoaderRoute: typeof PatientsPatientIdPlansRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/knowledge/voice/export': {
      id: '/knowledge/voice/export'
      path: '/export'
      fullPath: '/knowledge/voice/export'
      preLoaderRoute: typeof KnowledgeVoiceExportRouteImport
      parentRoute: typeof KnowledgeVoiceRoute
    }
    '/knowledge/voice/edit': {
      id: '/knowledge/voice/edit'
      path: '/edit'
      fullPath: '/knowledge/voice/edit'
      preLoaderRoute: typeof KnowledgeVoiceEditRouteImport
      parentRoute: typeof KnowledgeVoiceRoute
    }
    '/knowledge/voice/create': {
      id: '/knowledge/voice/create'
      path: '/create'
      fullPath: '/knowledge/voice/create'
      preLoaderRoute: typeof KnowledgeVoiceCreateRouteImport
      parentRoute: typeof KnowledgeVoiceRoute
    }
    '/knowledge/sequence/export': {
      id: '/knowledge/sequence/export'
      path: '/export'
      fullPath: '/knowledge/sequence/export'
      preLoaderRoute: typeof KnowledgeSequenceExportRouteImport
      parentRoute: typeof KnowledgeSequenceRoute
    }
    '/knowledge/sequence/edit': {
      id: '/knowledge/sequence/edit'
      path: '/edit'
      fullPath: '/knowledge/sequence/edit'
      preLoaderRoute: typeof KnowledgeSequenceEditRouteImport
      parentRoute: typeof KnowledgeSequenceRoute
    }
    '/knowledge/sequence/create': {
      id: '/knowledge/sequence/create'
      path: '/create'
      fullPath: '/knowledge/sequence/create'
      preLoaderRoute: typeof KnowledgeSequenceCreateRouteImport
      parentRoute: typeof KnowledgeSequenceRoute
    }
    '/knowledge/motion/export': {
      id: '/knowledge/motion/export'
      path: '/export'
      fullPath: '/knowledge/motion/export'
      preLoaderRoute: typeof KnowledgeMotionExportRouteImport
      parentRoute: typeof KnowledgeMotionRoute
    }
    '/knowledge/motion/edit': {
      id: '/knowledge/motion/edit'
      path: '/edit'
      fullPath: '/knowledge/motion/edit'
      preLoaderRoute: typeof KnowledgeMotionEditRouteImport
      parentRoute: typeof KnowledgeMotionRoute
    }
    '/knowledge/motion/create': {
      id: '/knowledge/motion/create'
      path: '/create'
      fullPath: '/knowledge/motion/create'
      preLoaderRoute: typeof KnowledgeMotionCreateRouteImport
      parentRoute: typeof KnowledgeMotionRoute
    }
    '/knowledge/library/export': {
      id: '/knowledge/library/export'
      path: '/export'
      fullPath: '/knowledge/library/export'
      preLoaderRoute: typeof KnowledgeLibraryExportRouteImport
      parentRoute: typeof KnowledgeLibraryRoute
    }
    '/knowledge/library/edit': {
      id: '/knowledge/library/edit'
      path: '/edit'
      fullPath: '/knowledge/library/edit'
      preLoaderRoute: typeof KnowledgeLibraryEditRouteImport
      parentRoute: typeof KnowledgeLibraryRoute
    }
    '/knowledge/library/create': {
      id: '/knowledge/library/create'
      path: '/create'
      fullPath: '/knowledge/library/create'
      preLoaderRoute: typeof KnowledgeLibraryCreateRouteImport
      parentRoute: typeof KnowledgeLibraryRoute
    }
    '/campus/maps/$mapId': {
      id: '/campus/maps/$mapId'
      path: '/$mapId'
      fullPath: '/campus/maps/$mapId'
      preLoaderRoute: typeof CampusMapsMapIdRouteImport
      parentRoute: typeof CampusMapsRoute
    }
    '/campus/beds/$bedId': {
      id: '/campus/beds/$bedId'
      path: '/$bedId'
      fullPath: '/campus/beds/$bedId'
      preLoaderRoute: typeof CampusBedsBedIdRouteImport
      parentRoute: typeof CampusBedsRoute
    }
    '/patients/$patientId/plans/': {
      id: '/patients/$patientId/plans/'
      path: '/'
      fullPath: '/patients/$patientId/plans/'
      preLoaderRoute: typeof PatientsPatientIdPlansIndexRouteImport
      parentRoute: typeof PatientsPatientIdPlansRoute
    }
    '/patients/$patientId/plans/export': {
      id: '/patients/$patientId/plans/export'
      path: '/export'
      fullPath: '/patients/$patientId/plans/export'
      preLoaderRoute: typeof PatientsPatientIdPlansExportRouteImport
      parentRoute: typeof PatientsPatientIdPlansRoute
    }
    '/patients/$patientId/plans/edit': {
      id: '/patients/$patientId/plans/edit'
      path: '/edit'
      fullPath: '/patients/$patientId/plans/edit'
      preLoaderRoute: typeof PatientsPatientIdPlansEditRouteImport
      parentRoute: typeof PatientsPatientIdPlansRoute
    }
    '/patients/$patientId/plans/create': {
      id: '/patients/$patientId/plans/create'
      path: '/create'
      fullPath: '/patients/$patientId/plans/create'
      preLoaderRoute: typeof PatientsPatientIdPlansCreateRouteImport
      parentRoute: typeof PatientsPatientIdPlansRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions': {
      id: '/patients/$patientId/plans/$planId/prescriptions'
      path: '/$planId/prescriptions'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRouteImport
      parentRoute: typeof PatientsPatientIdPlansRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/': {
      id: '/patients/$patientId/plans/$planId/prescriptions/'
      path: '/'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsIndexRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/export': {
      id: '/patients/$patientId/plans/$planId/prescriptions/export'
      path: '/export'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/export'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsExportRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/edit': {
      id: '/patients/$patientId/plans/$planId/prescriptions/edit'
      path: '/edit'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/edit'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsEditRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/create': {
      id: '/patients/$patientId/plans/$planId/prescriptions/create'
      path: '/create'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/create'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsCreateRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current': {
      id: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current'
      path: '/$prescriptionId/current'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/': {
      id: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/'
      path: '/'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit': {
      id: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit'
      path: '/edit'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/edit'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute
    }
    '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create': {
      id: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create'
      path: '/create'
      fullPath: '/patients/$patientId/plans/$planId/prescriptions/$prescriptionId/current/create'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRouteImport
      parentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute
    }
  }
}

interface CampusBedsRouteChildren {
  CampusBedsBedIdRoute: typeof CampusBedsBedIdRoute
  CampusBedsIndexRoute: typeof CampusBedsIndexRoute
}

const CampusBedsRouteChildren: CampusBedsRouteChildren = {
  CampusBedsBedIdRoute: CampusBedsBedIdRoute,
  CampusBedsIndexRoute: CampusBedsIndexRoute,
}

const CampusBedsRouteWithChildren = CampusBedsRoute._addFileChildren(
  CampusBedsRouteChildren,
)

interface CampusMapsRouteChildren {
  CampusMapsMapIdRoute: typeof CampusMapsMapIdRoute
  CampusMapsIndexRoute: typeof CampusMapsIndexRoute
}

const CampusMapsRouteChildren: CampusMapsRouteChildren = {
  CampusMapsMapIdRoute: CampusMapsMapIdRoute,
  CampusMapsIndexRoute: CampusMapsIndexRoute,
}

const CampusMapsRouteWithChildren = CampusMapsRoute._addFileChildren(
  CampusMapsRouteChildren,
)

interface CampusRouteChildren {
  CampusBedsRoute: typeof CampusBedsRouteWithChildren
  CampusMapsRoute: typeof CampusMapsRouteWithChildren
  CampusIndexRoute: typeof CampusIndexRoute
}

const CampusRouteChildren: CampusRouteChildren = {
  CampusBedsRoute: CampusBedsRouteWithChildren,
  CampusMapsRoute: CampusMapsRouteWithChildren,
  CampusIndexRoute: CampusIndexRoute,
}

const CampusRouteWithChildren =
  CampusRoute._addFileChildren(CampusRouteChildren)

interface KnowledgeLibraryRouteChildren {
  KnowledgeLibraryCreateRoute: typeof KnowledgeLibraryCreateRoute
  KnowledgeLibraryEditRoute: typeof KnowledgeLibraryEditRoute
  KnowledgeLibraryExportRoute: typeof KnowledgeLibraryExportRoute
  KnowledgeLibraryIndexRoute: typeof KnowledgeLibraryIndexRoute
}

const KnowledgeLibraryRouteChildren: KnowledgeLibraryRouteChildren = {
  KnowledgeLibraryCreateRoute: KnowledgeLibraryCreateRoute,
  KnowledgeLibraryEditRoute: KnowledgeLibraryEditRoute,
  KnowledgeLibraryExportRoute: KnowledgeLibraryExportRoute,
  KnowledgeLibraryIndexRoute: KnowledgeLibraryIndexRoute,
}

const KnowledgeLibraryRouteWithChildren =
  KnowledgeLibraryRoute._addFileChildren(KnowledgeLibraryRouteChildren)

interface KnowledgeMotionRouteChildren {
  KnowledgeMotionCreateRoute: typeof KnowledgeMotionCreateRoute
  KnowledgeMotionEditRoute: typeof KnowledgeMotionEditRoute
  KnowledgeMotionExportRoute: typeof KnowledgeMotionExportRoute
  KnowledgeMotionIndexRoute: typeof KnowledgeMotionIndexRoute
}

const KnowledgeMotionRouteChildren: KnowledgeMotionRouteChildren = {
  KnowledgeMotionCreateRoute: KnowledgeMotionCreateRoute,
  KnowledgeMotionEditRoute: KnowledgeMotionEditRoute,
  KnowledgeMotionExportRoute: KnowledgeMotionExportRoute,
  KnowledgeMotionIndexRoute: KnowledgeMotionIndexRoute,
}

const KnowledgeMotionRouteWithChildren = KnowledgeMotionRoute._addFileChildren(
  KnowledgeMotionRouteChildren,
)

interface KnowledgeSequenceRouteChildren {
  KnowledgeSequenceCreateRoute: typeof KnowledgeSequenceCreateRoute
  KnowledgeSequenceEditRoute: typeof KnowledgeSequenceEditRoute
  KnowledgeSequenceExportRoute: typeof KnowledgeSequenceExportRoute
  KnowledgeSequenceIndexRoute: typeof KnowledgeSequenceIndexRoute
}

const KnowledgeSequenceRouteChildren: KnowledgeSequenceRouteChildren = {
  KnowledgeSequenceCreateRoute: KnowledgeSequenceCreateRoute,
  KnowledgeSequenceEditRoute: KnowledgeSequenceEditRoute,
  KnowledgeSequenceExportRoute: KnowledgeSequenceExportRoute,
  KnowledgeSequenceIndexRoute: KnowledgeSequenceIndexRoute,
}

const KnowledgeSequenceRouteWithChildren =
  KnowledgeSequenceRoute._addFileChildren(KnowledgeSequenceRouteChildren)

interface KnowledgeVoiceRouteChildren {
  KnowledgeVoiceCreateRoute: typeof KnowledgeVoiceCreateRoute
  KnowledgeVoiceEditRoute: typeof KnowledgeVoiceEditRoute
  KnowledgeVoiceExportRoute: typeof KnowledgeVoiceExportRoute
  KnowledgeVoiceIndexRoute: typeof KnowledgeVoiceIndexRoute
}

const KnowledgeVoiceRouteChildren: KnowledgeVoiceRouteChildren = {
  KnowledgeVoiceCreateRoute: KnowledgeVoiceCreateRoute,
  KnowledgeVoiceEditRoute: KnowledgeVoiceEditRoute,
  KnowledgeVoiceExportRoute: KnowledgeVoiceExportRoute,
  KnowledgeVoiceIndexRoute: KnowledgeVoiceIndexRoute,
}

const KnowledgeVoiceRouteWithChildren = KnowledgeVoiceRoute._addFileChildren(
  KnowledgeVoiceRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeLibraryRoute: typeof KnowledgeLibraryRouteWithChildren
  KnowledgeMotionRoute: typeof KnowledgeMotionRouteWithChildren
  KnowledgeQaRoute: typeof KnowledgeQaRoute
  KnowledgeSequenceRoute: typeof KnowledgeSequenceRouteWithChildren
  KnowledgeVoiceRoute: typeof KnowledgeVoiceRouteWithChildren
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeLibraryRoute: KnowledgeLibraryRouteWithChildren,
  KnowledgeMotionRoute: KnowledgeMotionRouteWithChildren,
  KnowledgeQaRoute: KnowledgeQaRoute,
  KnowledgeSequenceRoute: KnowledgeSequenceRouteWithChildren,
  KnowledgeVoiceRoute: KnowledgeVoiceRouteWithChildren,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface PatientsBaseRouteChildren {
  PatientsBaseCreateRoute: typeof PatientsBaseCreateRoute
  PatientsBaseEditRoute: typeof PatientsBaseEditRoute
  PatientsBaseExportRoute: typeof PatientsBaseExportRoute
  PatientsBaseIndexRoute: typeof PatientsBaseIndexRoute
}

const PatientsBaseRouteChildren: PatientsBaseRouteChildren = {
  PatientsBaseCreateRoute: PatientsBaseCreateRoute,
  PatientsBaseEditRoute: PatientsBaseEditRoute,
  PatientsBaseExportRoute: PatientsBaseExportRoute,
  PatientsBaseIndexRoute: PatientsBaseIndexRoute,
}

const PatientsBaseRouteWithChildren = PatientsBaseRoute._addFileChildren(
  PatientsBaseRouteChildren,
)

interface PatientsCurrentRouteChildren {
  PatientsCurrentCreateRoute: typeof PatientsCurrentCreateRoute
  PatientsCurrentEditRoute: typeof PatientsCurrentEditRoute
  PatientsCurrentIndexRoute: typeof PatientsCurrentIndexRoute
}

const PatientsCurrentRouteChildren: PatientsCurrentRouteChildren = {
  PatientsCurrentCreateRoute: PatientsCurrentCreateRoute,
  PatientsCurrentEditRoute: PatientsCurrentEditRoute,
  PatientsCurrentIndexRoute: PatientsCurrentIndexRoute,
}

const PatientsCurrentRouteWithChildren = PatientsCurrentRoute._addFileChildren(
  PatientsCurrentRouteChildren,
)

interface PatientsPlansRouteChildren {
  PatientsPlansCreateRoute: typeof PatientsPlansCreateRoute
  PatientsPlansEditRoute: typeof PatientsPlansEditRoute
  PatientsPlansExportRoute: typeof PatientsPlansExportRoute
  PatientsPlansIndexRoute: typeof PatientsPlansIndexRoute
}

const PatientsPlansRouteChildren: PatientsPlansRouteChildren = {
  PatientsPlansCreateRoute: PatientsPlansCreateRoute,
  PatientsPlansEditRoute: PatientsPlansEditRoute,
  PatientsPlansExportRoute: PatientsPlansExportRoute,
  PatientsPlansIndexRoute: PatientsPlansIndexRoute,
}

const PatientsPlansRouteWithChildren = PatientsPlansRoute._addFileChildren(
  PatientsPlansRouteChildren,
)

interface PatientsPrescriptionsRouteChildren {
  PatientsPrescriptionsCreateRoute: typeof PatientsPrescriptionsCreateRoute
  PatientsPrescriptionsEditRoute: typeof PatientsPrescriptionsEditRoute
  PatientsPrescriptionsExportRoute: typeof PatientsPrescriptionsExportRoute
  PatientsPrescriptionsIndexRoute: typeof PatientsPrescriptionsIndexRoute
}

const PatientsPrescriptionsRouteChildren: PatientsPrescriptionsRouteChildren = {
  PatientsPrescriptionsCreateRoute: PatientsPrescriptionsCreateRoute,
  PatientsPrescriptionsEditRoute: PatientsPrescriptionsEditRoute,
  PatientsPrescriptionsExportRoute: PatientsPrescriptionsExportRoute,
  PatientsPrescriptionsIndexRoute: PatientsPrescriptionsIndexRoute,
}

const PatientsPrescriptionsRouteWithChildren =
  PatientsPrescriptionsRoute._addFileChildren(
    PatientsPrescriptionsRouteChildren,
  )

interface PatientsReportsRouteChildren {
  PatientsReportsExportRoute: typeof PatientsReportsExportRoute
  PatientsReportsReviewRoute: typeof PatientsReportsReviewRoute
  PatientsReportsIndexRoute: typeof PatientsReportsIndexRoute
}

const PatientsReportsRouteChildren: PatientsReportsRouteChildren = {
  PatientsReportsExportRoute: PatientsReportsExportRoute,
  PatientsReportsReviewRoute: PatientsReportsReviewRoute,
  PatientsReportsIndexRoute: PatientsReportsIndexRoute,
}

const PatientsReportsRouteWithChildren = PatientsReportsRoute._addFileChildren(
  PatientsReportsRouteChildren,
)

interface PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteChildren {
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute
}

const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteChildren: PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteChildren =
  {
    PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentCreateRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentEditRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentIndexRoute,
  }

const PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteWithChildren =
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute._addFileChildren(
    PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteChildren,
  )

interface PatientsPatientIdPlansPlanIdPrescriptionsRouteChildren {
  PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute
  PatientsPatientIdPlansPlanIdPrescriptionsEditRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsEditRoute
  PatientsPatientIdPlansPlanIdPrescriptionsExportRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsExportRoute
  PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute
  PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteWithChildren
}

const PatientsPatientIdPlansPlanIdPrescriptionsRouteChildren: PatientsPatientIdPlansPlanIdPrescriptionsRouteChildren =
  {
    PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsCreateRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsEditRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsEditRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsExportRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsExportRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsIndexRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsPrescriptionIdCurrentRouteWithChildren,
  }

const PatientsPatientIdPlansPlanIdPrescriptionsRouteWithChildren =
  PatientsPatientIdPlansPlanIdPrescriptionsRoute._addFileChildren(
    PatientsPatientIdPlansPlanIdPrescriptionsRouteChildren,
  )

interface PatientsPatientIdPlansRouteChildren {
  PatientsPatientIdPlansCreateRoute: typeof PatientsPatientIdPlansCreateRoute
  PatientsPatientIdPlansEditRoute: typeof PatientsPatientIdPlansEditRoute
  PatientsPatientIdPlansExportRoute: typeof PatientsPatientIdPlansExportRoute
  PatientsPatientIdPlansIndexRoute: typeof PatientsPatientIdPlansIndexRoute
  PatientsPatientIdPlansPlanIdPrescriptionsRoute: typeof PatientsPatientIdPlansPlanIdPrescriptionsRouteWithChildren
}

const PatientsPatientIdPlansRouteChildren: PatientsPatientIdPlansRouteChildren =
  {
    PatientsPatientIdPlansCreateRoute: PatientsPatientIdPlansCreateRoute,
    PatientsPatientIdPlansEditRoute: PatientsPatientIdPlansEditRoute,
    PatientsPatientIdPlansExportRoute: PatientsPatientIdPlansExportRoute,
    PatientsPatientIdPlansIndexRoute: PatientsPatientIdPlansIndexRoute,
    PatientsPatientIdPlansPlanIdPrescriptionsRoute:
      PatientsPatientIdPlansPlanIdPrescriptionsRouteWithChildren,
  }

const PatientsPatientIdPlansRouteWithChildren =
  PatientsPatientIdPlansRoute._addFileChildren(
    PatientsPatientIdPlansRouteChildren,
  )

interface PatientsRouteChildren {
  PatientsBaseRoute: typeof PatientsBaseRouteWithChildren
  PatientsCurrentRoute: typeof PatientsCurrentRouteWithChildren
  PatientsPlansRoute: typeof PatientsPlansRouteWithChildren
  PatientsPrescriptionsRoute: typeof PatientsPrescriptionsRouteWithChildren
  PatientsReportsRoute: typeof PatientsReportsRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
  PatientsPatientIdPlansRoute: typeof PatientsPatientIdPlansRouteWithChildren
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsBaseRoute: PatientsBaseRouteWithChildren,
  PatientsCurrentRoute: PatientsCurrentRouteWithChildren,
  PatientsPlansRoute: PatientsPlansRouteWithChildren,
  PatientsPrescriptionsRoute: PatientsPrescriptionsRouteWithChildren,
  PatientsReportsRoute: PatientsReportsRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
  PatientsPatientIdPlansRoute: PatientsPatientIdPlansRouteWithChildren,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface RobotsRouteChildren {
  RobotsCreateRoute: typeof RobotsCreateRoute
  RobotsDetailRoute: typeof RobotsDetailRoute
  RobotsListRoute: typeof RobotsListRoute
  RobotsIndexRoute: typeof RobotsIndexRoute
}

const RobotsRouteChildren: RobotsRouteChildren = {
  RobotsCreateRoute: RobotsCreateRoute,
  RobotsDetailRoute: RobotsDetailRoute,
  RobotsListRoute: RobotsListRoute,
  RobotsIndexRoute: RobotsIndexRoute,
}

const RobotsRouteWithChildren =
  RobotsRoute._addFileChildren(RobotsRouteChildren)

interface TagsKnowledgeRouteChildren {
  TagsKnowledgeCreateRoute: typeof TagsKnowledgeCreateRoute
}

const TagsKnowledgeRouteChildren: TagsKnowledgeRouteChildren = {
  TagsKnowledgeCreateRoute: TagsKnowledgeCreateRoute,
}

const TagsKnowledgeRouteWithChildren = TagsKnowledgeRoute._addFileChildren(
  TagsKnowledgeRouteChildren,
)

interface TagsMotionRouteChildren {
  TagsMotionCreateRoute: typeof TagsMotionCreateRoute
}

const TagsMotionRouteChildren: TagsMotionRouteChildren = {
  TagsMotionCreateRoute: TagsMotionCreateRoute,
}

const TagsMotionRouteWithChildren = TagsMotionRoute._addFileChildren(
  TagsMotionRouteChildren,
)

interface TagsSequenceRouteChildren {
  TagsSequenceCreateRoute: typeof TagsSequenceCreateRoute
}

const TagsSequenceRouteChildren: TagsSequenceRouteChildren = {
  TagsSequenceCreateRoute: TagsSequenceCreateRoute,
}

const TagsSequenceRouteWithChildren = TagsSequenceRoute._addFileChildren(
  TagsSequenceRouteChildren,
)

interface TagsVoiceRouteChildren {
  TagsVoiceCreateRoute: typeof TagsVoiceCreateRoute
}

const TagsVoiceRouteChildren: TagsVoiceRouteChildren = {
  TagsVoiceCreateRoute: TagsVoiceCreateRoute,
}

const TagsVoiceRouteWithChildren = TagsVoiceRoute._addFileChildren(
  TagsVoiceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRouteWithChildren,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PatientsRoute: PatientsRouteWithChildren,
  PrescriptionsRoute: PrescriptionsRoute,
  ReportsRoute: ReportsRoute,
  RobotsRoute: RobotsRouteWithChildren,
  TagsKnowledgeRoute: TagsKnowledgeRouteWithChildren,
  TagsMotionRoute: TagsMotionRouteWithChildren,
  TagsSequenceRoute: TagsSequenceRouteWithChildren,
  TagsVoiceRoute: TagsVoiceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
